name: Build Flutter APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to latest checkout action

      - name: Debug: Print settings.gradle before update
        run: cat android/settings.gradle || true

      - name: Debug: Print build.gradle before update
        run: cat android/build.gradle || true

      - name: Update AGP version in settings.gradle
        run: |
          sed -i 's/id\s*["'']com\.android\.application["']\s*version\s*["'']8\.1\.[0-1]["']/id "com.android.application" version "8.6.0"/g' android/settings.gradle || true
          sed -i 's/id\s*'\''com\.android\.application'\''\s*version\s*'\''8\.1\.[0-1]'\''/id '\''com.android.application'\'' version '\''8.6.0'\''/g' android/settings.gradle || true

      - name: Update AGP version in build.gradle
        run: |
          sed -i 's/com\.android\.tools\.build:gradle:8\.1\.[0-1]/com.android.tools.build:gradle:8.6.0/g' android/build.gradle || true

      - name: Update Kotlin version in settings.gradle
        run: |
          sed -i 's/id\s*["'']org\.jetbrains\.kotlin\.android["']\s*version\s*["'']1\.8\.\w*["']/id "org.jetbrains.kotlin.android" version "2.1.0"/g' android/settings.gradle || true
          sed -i 's/id\s*'\''org\.jetbrains\.kotlin\.android'\''\s*version\s*'\''1\.8\.\w*'\''/id '\''org.jetbrains.kotlin.android'\'' version '\''2.1.0'\''/g' android/settings.gradle || true

      - name: Update Kotlin version in build.gradle
        run: |
          sed -i 's/ext\.kotlin_version\s*=\s*["'']1\.8\.\w*["']/ext.kotlin_version = "2.1.0"/g' android/build.gradle || true

      - name: Update Gradle Wrapper
        run: |
          sed -i 's/distributionUrl=https\\:\\/\\/services\.gradle\.org\\/distributions\\/gradle-[0-7]\.[0-9]\.[0-9]-/distributionUrl=https\\:\\/\\/services.gradle.org\\/distributions\\/gradle-8.3-bin.zip/g' android/gradle/wrapper/gradle-wrapper.properties || true

      - name: Debug: Print settings.gradle after update
        run: cat android/settings.gradle || true

      - name: Debug: Print build.gradle after update
        run: cat android/build.gradle || true

      - name: Setup Java (for keystore handling)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Create key.properties
        run: |
          cat <<EOF > android/key.properties
          storePassword=${{ secrets.STORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=../app/upload-keystore.jks
          EOF

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.3'  # Pinned to latest stable version
          architecture: 'x64'

      - name: Clear Flutter cache
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --android-skip-build-dependency-validation

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk