name: Build Flutter APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update AGP version in settings.gradle (multiple patterns)
        run: |
          # Essayer différents patterns pour l'AGP
          sed -i "s/8\.1\.0/8.6.0/g" android/settings.gradle || true
          sed -i "s/8\.1\.1/8.6.0/g" android/settings.gradle || true
          sed -i "s/8\.0\.[0-9]/8.6.0/g" android/settings.gradle || true
          sed -i "s/7\.[0-9]\.[0-9]/8.6.0/g" android/settings.gradle || true

      - name: Update AGP version in build.gradle (multiple patterns)
        run: |
          # Essayer différents patterns pour l'AGP
          sed -i "s/8\.1\.0/8.6.0/g" android/build.gradle || true
          sed -i "s/8\.1\.1/8.6.0/g" android/build.gradle || true
          sed -i "s/8\.0\.[0-9]/8.6.0/g" android/build.gradle || true
          sed -i "s/7\.[0-9]\.[0-9]/8.6.0/g" android/build.gradle || true
          # Pour le format classpath dans build.gradle
          sed -i "s/com\.android\.tools\.build:gradle:[0-9]\+\.[0-9]\+\.[0-9]\+/com.android.tools.build:gradle:8.6.0/g" android/build.gradle || true

      - name: Update Kotlin version in settings.gradle (multiple patterns)
        run: |
          sed -i "s/1\.8\.22/2.1.0/g" android/settings.gradle || true
          sed -i "s/1\.9\.[0-9]\+/2.1.0/g" android/settings.gradle || true
          sed -i "s/1\.8\.[0-9]\+/2.1.0/g" android/settings.gradle || true

      - name: Update Kotlin version in build.gradle (multiple patterns)
        run: |
          sed -i "s/1\.8\.22/2.1.0/g" android/build.gradle || true
          sed -i "s/1\.9\.[0-9]\+/2.1.0/g" android/build.gradle || true
          sed -i "s/1\.8\.[0-9]\+/2.1.0/g" android/build.gradle || true

      - name: Enable Core Library Desugaring
        run: |
          # Vérifier si le fichier app/build.gradle existe
          if [ -f "android/app/build.gradle" ]; then
            echo "Mise à jour de android/app/build.gradle pour activer le desugaring..."
            
            # Ajouter coreLibraryDesugaringEnabled = true dans compileOptions si pas déjà présent
            if ! grep -q "coreLibraryDesugaringEnabled" android/app/build.gradle; then
              sed -i '/compileOptions {/a\        coreLibraryDesugaringEnabled true' android/app/build.gradle
            fi
            
            # Ajouter la dépendance de desugaring si pas déjà présente
            if ! grep -q "com.android.tools:desugar_jdk_libs" android/app/build.gradle; then
              sed -i '/dependencies {/a\    coreLibraryDesugaring '\''com.android.tools:desugar_jdk_libs:2.0.4'\''' android/app/build.gradle
            fi
            
            # S'assurer que sourceCompatibility et targetCompatibility sont à Java 8 minimum
            sed -i 's/JavaVersion.VERSION_1_8/JavaVersion.VERSION_1_8/g' android/app/build.gradle
            
            echo "Desugaring activé avec succès"
          else
            echo "Fichier android/app/build.gradle non trouvé"
          fi

      - name: Verify build.gradle modifications
        run: |
          echo "=== Contenu de android/app/build.gradle (compileOptions) ==="
          grep -A 10 -B 2 "compileOptions" android/app/build.gradle || echo "compileOptions non trouvé"
          echo "=== Contenu de android/app/build.gradle (dependencies) ==="
          grep -A 5 -B 2 "dependencies" android/app/build.gradle || echo "dependencies non trouvé"
          echo "=== Recherche du desugaring ==="
          grep -n "desugar" android/app/build.gradle || echo "desugaring non trouvé"

      - name: Setup Java (for keystore handling)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Create key.properties
        run: |
          cat <<EOF > android/key.properties
          storePassword=${{ secrets.STORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=../app/upload-keystore.jks
          EOF

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: 'x64'

      - name: Clear Flutter cache
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --android-skip-build-dependency-validation